### ISSUE TITLE
batch_size_val

### ISSUE THREAD

**Issue by getcontrol** [ArmandDS/bert_for_long_text#4]
Where do the values 11, 187 come from in:

batch_size_val = **11**
batches_per_epoch_val = **187**

**Comment by ArmandDS** [comment]
Please read the article.

________________________________
De: getcontrol <notifications@github.com>
Enviado: sábado, 27 de junio de 2020 07:00 p. m.
Para: ArmandDS/bert_for_long_text <bert_for_long_text@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [ArmandDS/bert_for_long_text] batch_size_val (#4)


Where do the values 11, 187 come from in:

batch_size_val = 11
batches_per_epoch_val = 187
